apiVersion: v1
kind: Namespace
metadata:
  name: student-${STUDENT_ID}
  labels:
    lab: cloudsec
    student-id: "${STUDENT_ID}"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: student-quota
  namespace: student-${STUDENT_ID}
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "5"
