apiVersion: v1
kind: Pod
metadata:
  name: kali-attacker
  namespace: student-${STUDENT_ID}
  labels:
    app: kali
spec:
  containers:
  - name: kali
    image: kali-lab:latest
    imagePullPolicy: Never
    stdin: true
    tty: true
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"
    securityContext:
      capabilities:
        add: ["NET_RAW", "NET_ADMIN"]