apiVersion: v1
kind: Pod
metadata:
  name: target-metasploitable
  namespace: student-${STUDENT_ID}-target
  labels:
    app: target
spec:
  containers:
  - name: target
    image: metasploitable-lab:latest
    imagePullPolicy: Never
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"
    ports:
    - containerPort: 80
      name: http
